### ISSUE TITLE
CTF Time Write-up Link 404's

### ISSUE THREAD

**Issue by FSUMitch** [maxenced/Rot26-writeups#4]
Your link on the ctftime writeup for this question ([https://ctftime.org/writeup/7893](https://ctftime.org/writeup/7893)) 404's - it is [https://github.com/maxenced/Rot26-writeups/blob/master/CTF/hacklu/2017/crypto/salsa/README.md](https://github.com/maxenced/Rot26-writeups/blob/master/CTF/hacklu/2017/crypto/salsa/README.md) instead of [https://github.com/maxenced/Rot26-writeups/blob/master/CTF/Hacklu/2017/crypto/salsa/README.md](https://github.com/maxenced/Rot26-writeups/blob/master/CTF/Hacklu/2017/crypto/salsa/README.md)

**Comment by maxenced** [comment]
Hi, thanks for the report. We reorganized our repo a bit to be able to provide https://rot26.team , so I migrated our URLs to the new ones.
